apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-jupyterlab
  namespace: operators
spec:
  channel: alpha
  name: jupyterlab
  source: openaihub-catalog
  sourceNamespace: olm
